import complex_chaotic_behavior_solutions_functional_lemma_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace complex_chaotic_behavior_solutions_functional_lemma_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end complex_chaotic_behavior_solutions_functional_lemma_canonical_lane_mathlib
end HautevilleHouse
